version: '3'
services:
  muellplan_de-backend:
    image: muellplan_de-backend:v0.1.4
    networks:
    # backend and database should be in the same network
      - muellplan_de-network
    ports:
      - 3000:3000
    environment:
      DB_CON_HOST: YOUR_HOST
      DB_CON_PORT: YOUR_PORT
      DB_CON_USER: YOUR_USER
      DB_CON_PASSWORD: YOUR_PASSWORD
      DB_CON_DATABASE: muellplan_de # may be changed if you want to
    container_name: muellplan_de-backend
    restart: unless-stopped

networks:
  muellplan_de-network:
    external: true