name: muellplan_de_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  mysql1: ^0.20.0
  dotenv: ^4.1.0
  mailer: ^5.0.0
  cron: ^0.5.1
  ical: ^0.2.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
